name: auth0_spa_dart_example
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  auth0_spa_dart:
    path: ../

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
