name: auth0_spa_dart
description: A dart wrapper for auth0-spa-js
version: 1.0.1
repository: https://github.com/jfacoustic/Auth0-SPA-Dart

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  js: ^0.6.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
